name: microbusiness
channels:
  - defaults
dependencies:
  - python
  - numpy
  - anaconda::pandas
  - conda-forge::cudatoolkit
  - conda-forge::tensorflow-gpu
  - anaconda::scikit-learn
  - anaconda::statsmodels
  - conda-forge::jupyterlab
  - conda-forge::kaggle
  - conda-forge::matplotlib
  - anaconda::seaborn
  - conda-forge::multiprocessing-logging
  - conda-forge::pyarrow
  - conda-forge::geopandas