name: microbusiness
channels:
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - cudatoolkit
  - tensorflow-gpu
  - scikit-learn
  - statsmodels
  - jupyterlab
  - kaggle
  - matplotlib
  - seaborn
  - multiprocessing-logging
  - pyarrow
  - geopandas
