name: microbusiness
channels:
  - defaults
dependencies:
  - python=3.10.0
  - jupyterlab
  - tensorflow-gpu
  - kaggle
  - pandas
  - matplotlib
  - numpy
  - statsmodels
  - seaborn
  - scikit-learn
  - multiprocessing-logging
  - pyarrow
  - cudatoolkit
  - geopandas
